version: "3"

services:
  sonarqube:
    image: sonarqube:7.1-alpine
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  sonarqube-db:
    image: postgres:10.4-alpine
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data
      
  nexus3:
    image: "sonatype/nexus3:3.11.0"
    ports:
      - "8081:8081"
    environment:
      INSTALL4J_ADD_VM_PARAMS: |
        -Xms1200m -Xmx1200m -XX:MaxDirectMemorySize=2g -Djava.util.prefs.userRoot=/nexus-data/javaprefs
    volumes:
      - nexusdata:/nexus-data
      
  jenkins:
    image: jenkins/jenkins:lts
    environment:
      JAVA_OPTS: |
        -Djenkins.branch.WorkspaceLocatorImpl.PATH_MAX=6 -Dorg.apache.commons.jelly.tags.fmt.timeZone=Asia/Shanghai
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"

volumes:
  sonarqube_conf:
    driver: local
  sonarqube_data:
    driver: local
  sonarqube_extensions:
    driver: local
  sonarqube_bundled-plugins:
    driver: local
  postgresql:
    driver: local
  postgresql_data:
    driver: local
  nexusdata:
    driver: local
  jenkins_home:
    driver: local
