version: "3"
services:

  jenkins:
    image: jenkins/jenkins:lts-alpine
    environment:
      JAVA_OPTS: |
        -Djenkins.branch.WorkspaceLocatorImpl.PATH_MAX=6 -Dorg.apache.commons.jelly.tags.fmt.timeZone=Asia/Shanghai
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
      
      
volumes:
  jenkins_home:
    driver: local
